# Generated by Django 2.2.1 on 2019-06-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190601_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Thanh_Pho',
        ),
    ]
