# Generated by Django 2.2.2 on 2019-06-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=300)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
