# Generated by Django 2.2.2 on 2019-06-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20190622_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='thum',
            field=models.ImageField(default='', upload_to='uploads/Blog/logo/%Y/%m/%d/', verbose_name='Hình đại diện'),
        ),
    ]
