# Generated by Django 2.2.2 on 2019-06-29 07:39

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_page_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='des_cut',
            field=models.TextField(default='', max_length=300, verbose_name='Mô tả ngắn'),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Các từ khóa đươc phân cách bằng dấu phẩy (,)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Từ khóa'),
        ),
    ]
