# Generated by Django 2.2.2 on 2019-06-21 07:20

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KyNang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NganhNghe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ThanhPho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobPartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=300)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('skill', ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=300)),
                ('date_begin', models.DateTimeField()),
                ('duration', models.CharField(default='', max_length=100)),
                ('NS_tu', models.IntegerField(default='', verbose_name='Ngân sách từ ')),
                ('NS_den', models.IntegerField(default='', verbose_name='Ngân sách đến')),
                ('year_exp', models.CharField(default='', max_length=300, verbose_name='Số Năm Kinh Nghiệm')),
                ('location', models.CharField(default='', max_length=300, verbose_name='Hình thức làm việc')),
                ('file', models.FileField(default='', upload_to='uploads/ViecLamPartTime/file/%Y/%m/%d/', verbose_name='File đính kèm')),
                ('company_name', models.CharField(default='', max_length=300, verbose_name='Tên Công Ty')),
                ('hinh', models.ImageField(default='', upload_to='uploads/ViecLamPartTime/logo/%Y/%m/%d/', verbose_name='Logo Công Ty')),
                ('Nganh_Nghe', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vlance.NganhNghe', verbose_name='Chọn Nganh Nghe')),
                ('Thanh_Pho', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vlance.ThanhPho', verbose_name='Chọn Thành Phố')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=300)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('skill', models.TextField(default='', max_length=300)),
                ('last_date', models.DateTimeField()),
                ('NS_tu', models.DecimalField(decimal_places=3, default='', max_digits=50, verbose_name='Ngân sách từ')),
                ('NS_den', models.DecimalField(decimal_places=3, default='', max_digits=50, verbose_name='Ngân sách đến')),
                ('file', models.FileField(default='', upload_to='', verbose_name='File đính kèm')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('filled', models.BooleanField(default=False)),
                ('Nganh_Nghe', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vlance.NganhNghe', verbose_name='Chọn Nganh Nghe')),
                ('Thanh_Pho', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vlance.ThanhPho', verbose_name='Chọn Thành Phố')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='CVonsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('baogia', models.CharField(default='', max_length=300)),
                ('exp_info', models.TextField(default='', max_length=400)),
                ('dudinh_info', models.TextField(default='', max_length=400)),
                ('hotline', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=55)),
                ('file', models.FileField(default='', upload_to='uploads/CVonsite/file/%Y/%m/%d/', verbose_name='File đính kèm')),
                ('jobpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CVonsites', to='vlance.JobPartTime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('baogia', models.CharField(default='', max_length=300)),
                ('time', models.CharField(default='', max_length=300)),
                ('exp_info', models.TextField(default='', max_length=400)),
                ('dudinh_info', models.TextField(default='', max_length=400)),
                ('hotline', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=55)),
                ('file', models.FileField(default='', upload_to='uploads/baogia/file/%Y/%m/%d/', verbose_name='File đính kèm')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='vlance.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
