# Generated by Django 2.2.1 on 2019-06-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vlance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='website',
        ),
        migrations.RemoveField(
            model_name='nganhnghe',
            name='img',
        ),
        migrations.RemoveField(
            model_name='nganhnghe',
            name='text',
        ),
        migrations.AlterField(
            model_name='job',
            name='Nganh_Nghe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vlance.NganhNghe', verbose_name='Chọn Nganh Nghe'),
        ),
    ]
