# Generated by Django 2.2.2 on 2019-06-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vlance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='vlance.Job'),
        ),
    ]
