# Generated by Django 2.2.2 on 2019-06-21 08:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlance', '0002_auto_20190621_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
