# Generated by Django 2.2.1 on 2019-06-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('vlance', '0002_auto_20190609_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=300)),
                ('description', models.TextField(default='')),
                ('skill', models.TextField(default='', max_length=300)),
                ('date_begin', models.DateTimeField()),
                ('duration', models.CharField(default='', max_length=100)),
                ('NS_tu', models.IntegerField(default='', verbose_name='Ngân sách từ ')),
                ('NS_den', models.IntegerField(default='', verbose_name='Ngân sách đến')),
                ('year_exp', models.CharField(default='', max_length=300, verbose_name='Số Năm Kinh Nghiệm')),
                ('location', models.CharField(default='', max_length=300, verbose_name='Số Năm Kinh Nghiệm')),
                ('file', models.FileField(default='', upload_to='uploads/ViecLamPartTime/file/%Y/%m/%d/', verbose_name='File đính kèm')),
                ('company_name', models.CharField(default='', max_length=300, verbose_name='Tên Công Ty')),
                ('hinh', models.ImageField(default='', upload_to='uploads/ViecLamPartTime/logo/%Y/%m/%d/', verbose_name='Logo Công Ty')),
                ('Nganh_Nghe', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vlance.NganhNghe', verbose_name='Chọn Nganh Nghe')),
                ('Thanh_Pho', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vlance.ThanhPho', verbose_name='Chọn Thành Phố')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
