# Generated by Django 2.2.2 on 2019-06-21 09:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlance', '0003_auto_20190621_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skill',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=300),
        ),
    ]
