# Generated by Django 2.2.2 on 2019-06-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlance', '0003_jobparttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='baogia',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='applicant',
            name='dudinh_info',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='applicant',
            name='exp_info',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='applicant',
            name='file',
            field=models.FileField(default='', upload_to='uploads/baogia/file/%Y/%m/%d/', verbose_name='File đính kèm'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='time',
            field=models.CharField(default='', max_length=300),
        ),
    ]
