# Generated by Django 2.2.2 on 2019-06-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190621_1451'),
        ('vlance', '0004_auto_20190621_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvonsite',
            name='jobpt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CVonsites', to='vlance.Job'),
        ),
        migrations.CreateModel(
            name='GuiTBChapNhanJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('mess', models.CharField(default='', max_length=300)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applicant', to='vlance.Applicant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job', to='vlance.JobPartTime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
