# Generated by Django 2.2.2 on 2019-06-21 13:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlance', '0005_auto_20190621_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitbchapnhanjob',
            name='job',
        ),
        migrations.AlterField(
            model_name='guitbchapnhanjob',
            name='mess',
            field=ckeditor.fields.RichTextField(default='', max_length=300),
        ),
    ]
