# Generated by Django 2.2.2 on 2019-06-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vlance', '0006_auto_20190621_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvonsite',
            name='jobpt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CVonsites', to='vlance.JobPartTime'),
        ),
    ]
