# Generated by Django 2.2.2 on 2019-06-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlance', '0007_auto_20190622_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobparttime',
            name='filled',
            field=models.BooleanField(default=False),
        ),
    ]
