# Generated by Django 2.2.2 on 2019-06-21 18:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190621_1451'),
        ('vlance', '0008_jobparttime_filled'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiTBChapNhanJobpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('mess', ckeditor.fields.RichTextField(default='', max_length=300)),
                ('cvonsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CVonsite', to='vlance.CVonsite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
