# Generated by Django 2.2.2 on 2019-06-27 11:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190621_1451'),
        ('vlance', '0009_guitbchapnhanjobpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuocThi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(default='', max_length=255)),
                ('linh_vuc', models.CharField(default='Các việc thiết kế khác', max_length=300)),
                ('title', models.CharField(default='', max_length=300)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('last_date', models.DateTimeField()),
                ('gt', models.DecimalField(decimal_places=3, default='500.000', max_digits=50, verbose_name='Giải thưởng ')),
                ('file', models.FileField(default='', upload_to='uploads/ViecLamPartTime/file/%Y/%m/%d/', verbose_name='File đính kèm')),
                ('filled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
