# Generated by Django 2.2.2 on 2019-06-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlance', '0010_cuocthi'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitbchapnhanjobpt',
            name='filled',
            field=models.BooleanField(default=False),
        ),
    ]
