# Generated by Django 2.2.2 on 2019-06-29 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlance', '0011_guitbchapnhanjobpt_filled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitbchapnhanjobpt',
            name='filled',
        ),
    ]
