# Generated by Django 2.2.2 on 2019-07-03 23:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190628_0343'),
        ('vlance', '0012_remove_guitbchapnhanjobpt_filled'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiThi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ynghia', models.TextField(default='', max_length=400)),
                ('hinh1', models.ImageField(default='uploads/User/unknown.png', upload_to='uploads/CuocThi/hinh/%Y/%m/%d/', verbose_name='File đính kèm')),
                ('hinh2', models.ImageField(default='uploads/User/unknown.png', upload_to='uploads/CuocThi/hinh/%Y/%m/%d/', verbose_name='File đính kèm')),
                ('hinh3', models.ImageField(default='uploads/User/unknown.png', upload_to='uploads/CuocThi/hinh/%Y/%m/%d/', verbose_name='File đính kèm')),
            ],
            options={
                'verbose_name_plural': 'Danh Sách Bài Dự Thi',
            },
        ),
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name_plural': 'Báo Giá Việc Dự Án'},
        ),
        migrations.AlterModelOptions(
            name='cuocthi',
            options={'verbose_name_plural': 'Đăng Cuộc Thi'},
        ),
        migrations.AlterModelOptions(
            name='cvonsite',
            options={'verbose_name_plural': 'Báo giá việc làm Part Time'},
        ),
        migrations.AlterModelOptions(
            name='guitbchapnhanjob',
            options={'verbose_name_plural': 'Thông báo chấp nhận dự án'},
        ),
        migrations.AlterModelOptions(
            name='guitbchapnhanjobpt',
            options={'verbose_name_plural': 'Thông báo chấp nhận công việc'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'Đăng Dự Án'},
        ),
        migrations.AlterModelOptions(
            name='jobparttime',
            options={'verbose_name_plural': 'Đăng Việc PartTime'},
        ),
        migrations.AlterModelOptions(
            name='kynang',
            options={'verbose_name_plural': 'Kỹ Năng'},
        ),
        migrations.AlterModelOptions(
            name='nganhnghe',
            options={'verbose_name_plural': 'Ngành Nghề - Lĩnh Vực'},
        ),
        migrations.AlterModelOptions(
            name='thanhpho',
            options={'verbose_name_plural': 'Thành Phố'},
        ),
        migrations.CreateModel(
            name='GuiTBChapNhanct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('mess', ckeditor.fields.RichTextField(default='', max_length=300)),
                ('bt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BaiThi', to='vlance.BaiThi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
            options={
                'verbose_name_plural': 'Thông báo chấp nhận công việc',
            },
        ),
        migrations.AddField(
            model_name='baithi',
            name='ct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BaiThi', to='vlance.CuocThi'),
        ),
        migrations.AddField(
            model_name='baithi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
