# Generated by Django 2.2.1 on 2019-06-01 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vlance', '0002_auto_20190601_1228'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Thanh_Pho',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vlance.ThanhPho', verbose_name='Chọn Thành Phố'),
        ),
        migrations.AddField(
            model_name='user',
            name='hotline',
            field=models.CharField(default='', max_length=15),
        ),
    ]
