# Generated by Django 2.2.2 on 2019-06-18 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vlance', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nganh_nghes',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vlance.NganhNghe', verbose_name='Chọn Nganh Nghe'),
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.ManyToManyField(default='', null=True, to='vlance.KyNang', verbose_name='Chọn kỹ năng'),
        ),
        migrations.AddField(
            model_name='user',
            name='thanh_phos',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vlance.ThanhPho', verbose_name='Chọn Thành Phố'),
        ),
    ]
