# Generated by Django 2.2.2 on 2019-06-21 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190621_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nganh_nghes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vlance.NganhNghe', verbose_name='Chọn Ngành Nghề'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thanh_phos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vlance.ThanhPho', verbose_name='Chọn Thành Phố'),
        ),
    ]
