# Generated by Django 2.2.2 on 2019-06-18 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190618_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300, null=True, verbose_name='Giới Thiệu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hinh',
            field=models.ImageField(default='uploads/User/unknown.png', null=True, upload_to='uploads/User/avatar/%Y/%m/%d/', verbose_name='Avatar '),
        ),
        migrations.AlterField(
            model_name='user',
            name='nganh_nghes',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='vlance.NganhNghe', verbose_name='Chọn Ngành Nghề'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sologan',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Chức danh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thanh_phos',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='vlance.ThanhPho', verbose_name='Chọn Thành Phố'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_exp',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Trình Độ'),
        ),
    ]
