# Generated by Django 2.2.2 on 2019-06-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190621_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.ManyToManyField(default='', to='vlance.KyNang', verbose_name='Chọn kỹ năng'),
        ),
    ]
